export type Locale = 'en' | 'ua' | 'pl'

export const translations = {
  en: {
    common: { back: 'Back', work: 'Work', projects: 'projects', watchProject: 'Watch Project', playFullVideo: 'Play full video', closeProject: 'Close project', selectedWork: 'SELECTED WORK', categories: 'Work categories' },
    work: { eyebrow: 'SELECTED WORK', title: 'Explore my creative', titleAccent: 'worlds.', description: 'A selection of logo animations and brand motion systems crafted to make identities move.' },
    categories: { 'logo-animation': 'Logo Animation', icons: 'Icons', 'brand-motion': 'Brand Motion', 'lottie-ui': 'Lottie UI', 'social-media': 'Social Media', posters: 'Posters' },
    categoryCards: { 'logo-animation': 'Cinematic logo reveals and animated brand marks.', 'brand-motion': 'Motion systems for identities and branded moments.', 'lottie-ui': 'Product interfaces brought to life with purposeful motion.', 'social-media': 'Short motion pieces for campaigns and social platforms.', posters: 'Experimental visuals and additional motion projects.' },
    navigation: { home: 'Home', work: 'Work', about: 'About', process: 'Process', testimonials: 'Testimonials', faq: 'FAQ', contact: 'Contact', main: 'Main navigation', sections: 'Section navigation', language: 'Language', contactCta: "Let's talk" },
    modal: { format: 'Format', software: 'Software', delivery: 'Delivery' },
    sections: {
      hero: { eyebrow: 'MOTION DESIGNER', line1: 'I bring brands', line2: 'to life through', accent: 'motion', description: 'I design premium logo animations and brand motion systems that make businesses unforgettable.', viewWork: 'View my work', showreel: 'Watch showreel', available: 'Available for new projects', worldwide: 'Worldwide', trustedBy: 'Design for brands' },
      about: { eyebrow: 'ABOUT', title: 'Motion design with', clarity: 'clarity', rhythm: 'rhythm', purpose: 'purpose.', description: 'I craft refined motion experiences that communicate ideas, elevate brands and connect with people. Every project is designed with intention and animated with precision.', focusAreas: 'Motion design focus areas', values: ['Logo Animation', 'Brand Motion', 'Social Content'], stats: ['Years experience', 'Projects delivered', 'Clients worldwide'], statsLabel: 'Motion design experience stats' },
      process: { eyebrow: 'PROCESS', title: 'My creative', accent: 'process', description: 'A clear, collaborative process that turns a strong idea into motion with purpose.', steps: [{ title: 'Discover', description: 'Define the brand, audience, formats and desired motion behavior.' }, { title: 'Design', description: 'Build a visual direction with clean hierarchy and flexible production rules.' }, { title: 'Animate', description: 'Shape timing, transitions and visual rhythm for the final system.' }, { title: 'Deliver', description: 'Prepare final exports and organized assets for future use.' }] },
      testimonials: { eyebrow: 'TESTIMONIALS', title: 'Trusted by teams that value', accent: 'precision.', description: 'A few words from clients who value thoughtful motion, clear communication and exceptional craft.', items: [{ quote: 'The motion work brought clarity to our identity and made every touchpoint feel intentional.', role: 'Brand Lead, Onyx' }, { quote: 'A rare combination of sharp design thinking, craft and a genuinely smooth creative process.', role: 'Founder, North Studio' }, { quote: 'Every animation had purpose. The final system felt premium, clear and ready to scale.', role: 'Product Director, Elevate' }] },
      faq: { eyebrow: 'FAQ', title: 'Simple answers before the', accent: 'first brief.', description: 'The most common questions, answered simply so you know what to expect before we begin.', items: [{ question: 'What motion projects do you create?', answer: 'I specialize in 2D logo animation, transitions, and motion design graphics.' }, { question: 'How does a project usually start?', answer: 'We start with a brief, discussing your brand identity, goals, and visual ideas before moving to storyboarding and animation.' }, { question: 'How long does a project take?', answer: 'A standard logo animation typically takes 3 to 7 business days depending on complexity and revision rounds.' }, { question: 'Can you work with an existing brand system?', answer: 'Yes, absolutely. I adapt the animation style to perfectly match your current brand guidelines, colors, and assets.' }] },
      contact: { eyebrow: 'CONTACT', heading: "Let's create something amazing.", title: "Let’s create something", accent: 'amazing.', description: "Have a project in mind? I’d love to hear about it. Tell me a little about your idea and let’s make something meaningful together.", name: 'Name', email: 'Email', projectType: 'Project type', budget: 'Budget / Timeline', message: 'Message', send: 'Send message', disclaimer: 'Your information is safe and will never be shared.', connect: 'Connect', socialLinks: 'Social links', successHeading: 'Thank you!', successMessage: "Your message has been sent successfully. We'll be in touch soon.", resetButton: 'Send another message', projectTypes: ['Logo animation', 'Brand motion system', 'Social content', 'Lottie / UI motion', 'Other'], budgets: ['Quick piece / 1-2 weeks', 'Campaign / 2-4 weeks', 'Brand system / 4+ weeks', 'Not sure yet'] },
      footer: { tagline: 'Motion design portfolio foundation.', socialLinks: 'Social links', copyright: '© 2026 VALENTYN LAVRYK · MOTION DESIGNER' },
    },
  },
  ua: {
    common: { back: 'Назад', work: 'Роботи', projects: 'проєктів', watchProject: 'Переглянути проєкт', playFullVideo: 'Відтворити відео', closeProject: 'Закрити проєкт', selectedWork: 'ВИБРАНІ РОБОТИ', categories: 'Категорії робіт' },
    work: { eyebrow: 'ВИБРАНІ РОБОТИ', title: 'Дослідіть мої творчі', titleAccent: 'світи.', description: 'Добірка анімацій логотипів і бренд-систем, які оживляють айдентику.' },
    categories:
      { 'logo-animation': 'Анімація логотипів', icons: 'Icons', 'brand-motion': 'Бренд-моушн', 'lottie-ui': 'Lottie UI', 'social-media': 'Соціальні мережі', posters: 'Постери' },
    categoryCards: { 'logo-animation': 'Кінематографічні анімації логотипів і фірмових знаків.', 'brand-motion': 'Моушн-системи для айдентики та брендових моментів.', 'lottie-ui': 'Інтерфейси продуктів, оживлені змістовною анімацією.', 'social-media': 'Короткі моушн-відео для кампаній і соцмереж.', posters: 'Експериментальні візуальні та додаткові моушн-проєкти.' },
    navigation: { home: 'Головна', work: 'Роботи', about: 'Про мене', process: 'Процес', testimonials: 'Відгуки', faq: 'FAQ', contact: 'Контакти', main: 'Головна навігація', sections: 'Навігація розділами', language: 'Мова', contactCta: 'Поговорімо' },
    modal: { format: 'Формат', software: 'Програми', delivery: 'Доставка' },
    sections: {
      hero: { eyebrow: 'МОУШН-ДИЗАЙНЕР', line1: 'Я оживляю бренди', line2: 'за допомогою', accent: 'анімації', description: 'Я створюю преміальні анімації логотипів і моушн-системи, які роблять бізнес упізнаваним.', viewWork: 'Переглянути роботи', showreel: 'Дивитися шоуріл', available: 'Відкритий до нових проєктів', worldwide: 'По всьому світу', trustedBy: 'Дизайн для брендів' },
      about: { eyebrow: 'ПРО МЕНЕ', title: 'Моушн-дизайн із', clarity: 'ясністю', rhythm: 'ритмом', purpose: 'метою.', description: 'Я створюю вишукані моушн-рішення, які передають ідеї, посилюють бренди та об’єднують людей. Кожен проєкт продуманий і точно анімований.', focusAreas: 'Напрями моушн-дизайну', values: ['Анімація логотипів', 'Бренд-моушн', 'Контент для соцмереж'], stats: ['Років досвіду', 'Реалізованих проєктів', 'Клієнтів у світі'], statsLabel: 'Статистика досвіду' },
      process: { eyebrow: 'ПРОЦЕС', title: 'Мій творчий', accent: 'процес', description: 'Зрозумілий спільний процес, що перетворює сильну ідею на змістовну анімацію.', steps: [{ title: 'Дослідження', description: 'Визначаємо бренд, аудиторію, формати та бажану поведінку анімації.' }, { title: 'Дизайн', description: 'Створюємо візуальний напрям із чіткою ієрархією та гнучкими правилами.' }, { title: 'Анімація', description: 'Формуємо таймінг, переходи та візуальний ритм фінальної системи.' }, { title: 'Передача', description: 'Готуємо фінальні експорти й упорядковані матеріали для подальшого використання.' }] },
      testimonials: { eyebrow: 'ВІДГУКИ', title: 'Нам довіряють команди, що цінують', accent: 'точність.', description: 'Кілька слів від клієнтів, які цінують продуману анімацію, чітку комунікацію та майстерність.', items: [{ quote: 'Моушн-дизайн додав нашій айдентиці ясності й зробив кожну точку контакту продуманою.', role: 'Бренд-лідер, Onyx' }, { quote: 'Рідкісне поєднання сильного дизайн-мислення, майстерності та справді комфортного творчого процесу.', role: 'Засновник, North Studio' }, { quote: 'Кожна анімація мала мету. Фінальна система вийшла преміальною, зрозумілою та масштабованою.', role: 'Продуктова директорка, Elevate' }] },
      faq: { eyebrow: 'ЗАПИТАННЯ', title: 'Прості відповіді перед', accent: 'першим брифом.', description: 'Найпоширеніші запитання та прості відповіді, щоб ви знали, чого очікувати.', items: [{ question: 'Які моушн-проєкти ви створюєте?', answer: 'Я спеціалізуюся на 2D анімації логотипів, переходах та графіці моушн-дизайну.' }, { question: 'Як зазвичай починається проєкт?', answer: 'Ми починаємо з брифу, обговорення айдентики вашого бренду, цілей та візуальних ідей перед переходом до розкадровки та анімації.' }, { question: 'Скільки часу займає проєкт?', answer: 'Стандартна анімація логотипу зазвичай займає від 3 до 7 робочих днів залежно від складності та кількості правок.' }, { question: 'Чи можете ви працювати з готовою бренд-системою?', answer: 'Так, абсолютно. Я адаптую стиль анімації, щоб він ідеально відповідав вашим поточним гайдлайнам бренду, кольорам та елементам.' }] },
      contact: { eyebrow: 'КОНТАКТИ', heading: 'Давайте створимо щось дивовижне.', title: 'Створімо щось', accent: 'неймовірне.', description: 'Маєте ідею проєкту? Розкажіть трохи про неї — і створімо разом щось змістовне.', name: 'Ім’я', email: 'Email', projectType: 'Тип проєкту', budget: 'Бюджет / Терміни', message: 'Повідомлення', send: 'Надіслати', disclaimer: 'Ваша інформація захищена й ніколи не передаватиметься третім особам.', connect: 'Зв’язатися', socialLinks: 'Соціальні мережі', successHeading: 'Дякую!', successMessage: "Ваше повідомлення успішно надіслано. Скоро зв'яжемося з вами.", resetButton: 'Надіслати ще одне повідомлення', projectTypes: ['Анімація логотипу', 'Бренд-моушн система', 'Контент для соцмереж', 'Lottie / UI анімація', 'Інше'], budgets: ['Швидкий проєкт / 1–2 тижні', 'Кампанія / 2–4 тижні', 'Бренд-система / 4+ тижні', 'Ще не визначено'] },
      footer: { tagline: 'Портфоліо моушн-дизайнера.', socialLinks: 'Соціальні мережі', copyright: '© 2026 VALENTYN LAVRYK · МОУШН-ДИЗАЙНЕР' },
    },
  },
  pl: {
    common: { back: 'Wstecz', work: 'Prace', projects: 'projektów', watchProject: 'Obejrzyj projekt', playFullVideo: 'Odtwórz pełne wideo', closeProject: 'Zamknij projekt', selectedWork: 'WYBRANE PRACE', categories: 'Kategorie prac' },
    work: { eyebrow: 'WYBRANE PRACE', title: 'Poznaj moje kreatywne', titleAccent: 'światy.', description: 'Wybór animacji logo i systemów motion dla marek, które ożywiają identyfikację.' },
    categories: { 'logo-animation': 'Animacja logo', icons: 'Icons', 'brand-motion': 'Brand motion', 'lottie-ui': 'Lottie UI', 'social-media': 'Social media', posters: 'Plakaty' },
    categoryCards: { 'logo-animation': 'Kinowe animacje logo i znaków marki.', 'brand-motion': 'Systemy motion dla identyfikacji i marki.', 'lottie-ui': 'Interfejsy produktów ożywione przemyślanym ruchem.', 'social-media': 'Krótkie formy motion dla kampanii i social mediów.', posters: 'Eksperymentalne wizualizacje i dodatkowe projekty motion.' },
    navigation: { home: 'Start', work: 'Prace', about: 'O mnie', process: 'Proces', testimonials: 'Opinie', faq: 'FAQ', contact: 'Kontakt', main: 'Główna nawigacja', sections: 'Nawigacja sekcji', language: 'Język', contactCta: 'Porozmawiajmy' },
    modal: { format: 'Format', software: 'Oprogramowanie', delivery: 'Dostawa' },
    sections: {
      hero: { eyebrow: 'MOTION DESIGNER', line1: 'Ożywiam marki', line2: 'za pomocą', accent: 'ruchu', description: 'Projektuję wysokiej jakości animacje logo i systemy motion, dzięki którym marki zostają zapamiętane.', viewWork: 'Zobacz moje prace', showreel: 'Obejrzyj showreel', available: 'Dostępny dla nowych projektów', worldwide: 'Na całym świecie', trustedBy: 'Projektowanie dla marek' },
      about: { eyebrow: 'O MNIE', title: 'Motion design z', clarity: 'klarownością', rhythm: 'rytmem', purpose: 'celem.', description: 'Tworzę dopracowane doświadczenia motion, które komunikują idee, wzmacniają marki i łączą ludzi. Każdy projekt jest przemyślany i precyzyjnie animowany.', focusAreas: 'Obszary motion designu', values: ['Animacja logo', 'Brand motion', 'Treści social media'], stats: ['Lat doświadczenia', 'Zrealizowanych projektów', 'Klientów na świecie'], statsLabel: 'Statystyki doświadczenia' },
      process: { eyebrow: 'PROCES', title: 'Mój kreatywny', accent: 'proces', description: 'Jasny, oparty na współpracy proces, który zmienia mocny pomysł w celowy ruch.', steps: [{ title: 'Odkrywanie', description: 'Definiujemy markę, odbiorców, formaty i oczekiwane zachowanie animacji.' }, { title: 'Projektowanie', description: 'Budujemy kierunek wizualny z czytelną hierarchią i elastycznymi zasadami.' }, { title: 'Animacja', description: 'Kształtujemy timing, przejścia i rytm wizualny finalnego systemu.' }, { title: 'Przekazanie', description: 'Przygotowujemy finalne eksporty i uporządkowane materiały do dalszego użycia.' }] },
      testimonials: { eyebrow: 'OPINIE', title: 'Zaufały mi zespoły ceniące', accent: 'precyzję.', description: 'Kilka słów od klientów, którzy cenią przemyślany ruch, jasną komunikację i wyjątkowe wykonanie.', items: [{ quote: 'Motion design wniósł klarowność do naszej identyfikacji i sprawił, że każdy punkt styku stał się przemyślany.', role: 'Brand Lead, Onyx' }, { quote: 'Rzadkie połączenie świetnego myślenia projektowego, kunsztu i naprawdę płynnego procesu twórczego.', role: 'Założyciel, North Studio' }, { quote: 'Każda animacja miała cel. Finalny system był premium, przejrzysty i gotowy do skalowania.', role: 'Product Director, Elevate' }] },
      faq: { eyebrow: 'FAQ', title: 'Proste odpowiedzi przed', accent: 'pierwszym briefem.', description: 'Najczęstsze pytania i proste odpowiedzi, aby od początku było wiadomo, czego się spodziewać.', items: [{ question: 'Jakie projekty motion designu tworzysz?', answer: 'Specjalizuję się w animacji logo 2D, przejściach i grafice motion design.' }, { question: 'Jak zazwyczaj zaczyna się projekt?', answer: 'Zaczynamy od briefu, omawiając identyfikację wizualną Twojej marki, cele i pomysły, a następnie przechodzimy do scenopisu i animacji.' }, { question: 'Ile czasu zajmuje projekt?', answer: 'Standardowa animacja logo trwa zazwyczaj od 3 do 7 dni roboczych, w zależności od złożoności i rund poprawek.' }, { question: 'Czy możesz pracować z istniejącym systemem marki?', answer: 'Tak, absolutnie. Dostosowuję styl animacji tak, aby idealnie pasował do Twoich obecnych wytycznych marki, kolorów i materiałów.' }] },
      contact: { eyebrow: 'KONTAKT', heading: 'Stwórzmy coś niesamowitego.', title: 'Stwórzmy coś', accent: 'wyjątkowego.', description: 'Masz pomysł na projekt? Chętnie o nim usłyszę. Opowiedz mi o swojej idei i stwórzmy razem coś znaczącego.', name: 'Imię', email: 'Email', projectType: 'Typ projektu', budget: 'Budżet / Termin', message: 'Wiadomość', send: 'Wyślij wiadomość', disclaimer: 'Twoje informacje są bezpieczne i nigdy nie zostaną udostępnione.', connect: 'Kontakt', socialLinks: 'Linki społecznościowe', successHeading: 'Dziękuję!', successMessage: 'Twoja wiadomość została wysłana pomyślnie. Skontaktujemy się wkrótce.', resetButton: 'Wyślij kolejną wiadomość', projectTypes: ['Animacja logo', 'System brand motion', 'Treści social media', 'Lottie / UI motion', 'Inne'], budgets: ['Szybki projekt / 1–2 tygodnie', 'Kampania / 2–4 tygodnie', 'System marki / 4+ tygodnie', 'Jeszcze nie wiem'] },
      footer: { tagline: 'Portfolio motion designera.', socialLinks: 'Linki społecznościowe', copyright: '© 2026 VALENTYN LAVRYK · MOTION DESIGNER' },
    },
  },
} as const

export function localeFromPath(pathname: string): Locale {
  const segment = pathname.split('/')[1]
  return segment === 'ua' || segment === 'pl' ? segment : 'en'
}

export function localePrefix(locale: Locale) { return locale === 'en' ? '' : `/${locale}` }
