import type { PortfolioProject } from "../portfolioContent";

/*
 * LOGO ANIMATION - АДМІНКА
 * Тут тільки роботи категорії logo-animation
 * Щоб додати нову - скопіюй шаблон внизу
 */

export const logoAnimationProjects: PortfolioProject[] = [
  {
    // --- ТЕХНІЧНЕ ---
    id: "techlogo-motion", // 🚫 Унікальний ID
    slug: "techlogo-motion", // 🚫 Слаг URL
    category: "logo-animation", // 🚫 Має бути logo-animation

    // --- КОНТЕНТ ---
    title: "Techlogo", // ✅ Назва
    description: "Dynamic particle transformation into an interconnected tech symbol, completing with a sleek typographic reveal.", // ✅ Опис

    // --- МЕДІА (найчастіше міняєш тут) ---
    thumbnail: "/images/prewiew/logo/techlogo.webp", // ✅ Картинка картки
    video: "/videos/animation/logo/techlogo.webm", // ✅ Відео
    poster: "/images/projects/techlogo.webp", // ✅ Постер

    // --- ПОКАЗ ---
    showInMarquee: true, // ✅ true = в бігучій стрічці
    published: true, // ✅ true = на сайті
    order: 1, // ✅ Порядок 1,2,3...

    // --- МОДАЛКА ---
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Tech", "Abstract"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Techlogo Motion Reveal | VL Motion",
    seoDescription: "Dynamic particle transformation into an interconnected tech symbol, completing with a sleek typographic reveal.",
  },
  {
    id: "animation-designs-logo",
    slug: "Sahoo design",
    category: "logo-animation",
    title: "Sahoo_design",
    description: "Minimalist line dynamics leading into an infinity loop symbol with clean typography reveal.",
    thumbnail: "/images/prewiew/logo/Sahoo_design.webp",
    video: "/videos/animation/logo/Sahoo_design.webm",
    poster: "/images/prewiew/logo/Sahoo_design.webp",
    showInMarquee: true,
    published: true,
    order: 2,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Minimal", "Infinity"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    seoTitle: "Animation Designs Logo | VL Motion",
    seoDescription: "Minimalist line dynamics leading into an infinity loop symbol with clean typography reveal.",
  },
  {
    id: "pycha-kebs-logo",
    slug: "pycha-kebs-logo",
    category: "logo-animation",
    title: "Pycha Kebs",
    description: "Dynamic animation of a vertical spit and chef's knife forming a classic street food emblem with bold typography.",
    thumbnail: "/images/prewiew/logo/pycha.webp",
    video: "/videos/animation/logo/pycha.webm",
    poster: "/videos/animation/logo/pycha.webp",
    showInMarquee: true,
    published: true,
    order: 3,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Food", "Emblem", "Dynamic"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    seoTitle: "Pycha Kebs Emblem | VL Motion",
    seoDescription: "Dynamic animation of a vertical spit and chef's knife forming a classic street food emblem with bold typography.",
  },
  {
    id: "coolinart-logo",
    slug: "coolinart-logo",
    category: "logo-animation",
    title: "Coolinart",
    description: "Playful character-driven animation featuring a chef's hat and eyes that seamlessly transition into custom typography.",
    thumbnail: "/images/prewiew/logo/coolinart.webp",
    video: "/videos/animation/logo/coolinart.webm",
    poster: "/images/projects/coolinart.webp",
    showInMarquee: true,
    published: true,
    order: 4,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Character", "Playful", "Food"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:07",
    seoTitle: "Coolinart Identity Reveal | VL Motion",
    seoDescription: "Playful character-driven animation featuring a chef's hat and eyes that seamlessly transition into custom typography.",
  },
  {
    id: "foodtalk-logo",
    slug: "foodtalk-logo",
    category: "logo-animation",
    title: "Food Talk",
    description: "Minimalist animation starting with messaging indicators that morph into a speech bubble with integrated cutlery icons.",
    thumbnail: "/images/prewiew/logo/foodtalk.webp",
    video: "/videos/animation/logo/foodtalk.webm",
    poster: "/images/projects/foodtalk.webp",
    showInMarquee: true,
    published: true,
    order: 5,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Minimal", "Morphing", "UI"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:07",
    seoTitle: "Food Talk Concept | VL Motion",
    seoDescription: "Minimalist animation starting with messaging indicators that morph into a speech bubble with integrated cutlery icons.",
  },
  {
    id: "enigma-logo",
    slug: "enigma-logo",
    category: "logo-animation",
    title: "Enigma",
    description: "Geometric transformation of intersecting layers evolving into a complex, elegant pattern and luxury emblem.",
    thumbnail: "/images/prewiew/logo/enigma.webp",
    video: "/videos/animation/logo/enigma.webm",
    poster: "/images/projects/enigma.webp",
    showInMarquee: true,
    published: true,
    order: 6,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Geometric", "Luxury", "Pattern"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:10",
    seoTitle: "Enigma Logo Animation | VL Motion",
    seoDescription: "Geometric transformation of intersecting layers evolving into a complex, elegant pattern and luxury emblem.",
  },
  {
    id: "bbq-restaurant-logo",
    slug: "bbq-restaurant-logo",
    category: "logo-animation",
    title: "Barbecue Restaurant",
    description: "Constructivist geometric transitions resolving into a detailed vintage-style beef cattle logo badge.",
    thumbnail: "/images/prewiew/logo/bbq.webp",
    video: "/videos/animation/logo/bbq.webm",
    poster: "/images/projects/bbq.webp",
    showInMarquee: true,
    published: true,
    order: 7,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Vintage", "Badge", "Geometric"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Barbecue Restaurant Emblem | VL Motion",
    seoDescription: "Constructivist geometric transitions resolving into a detailed vintage-style beef cattle logo badge.",
  },
  {
    id: "frame-logo-motion",
    slug: "frame-logo-motion",
    category: "logo-animation",
    title: "Frame",
    description: "Camera focusing animation with green viewfinder corners revealing dynamic modern typography.",
    thumbnail: "/images/prewiew/logo/frame.webp",
    video: "/videos/animation/logo/frame.webm",
    poster: "/images/projects/frame.webp",
    showInMarquee: true,
    published: true,
    order: 8,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Tech", "Focus", "Clean"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:04",
    seoTitle: "Frame Focus Reveal | VL Motion",
    seoDescription: "Camera focusing animation with green viewfinder corners revealing dynamic modern typography.",
  },
  {
    id: "grant-heating-cooling",
    slug: "grant-heating-cooling",
    category: "logo-animation",
    title: "Grant Industrial",
    description: "Sleek fluid motion and dynamic swirl transitions revealing a corporate HVAC brand emblem.",
    thumbnail: "/images/prewiew/logo/grant.webp",
    video: "/videos/animation/logo/grant.webm",
    poster: "/images/projects/grant.webp",
    showInMarquee: false,
    published: true,
    order: 9,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Corporate", "Fluid", "HVAC"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Grant Industrial Identity | VL Motion",
    seoDescription: "Sleek fluid motion and dynamic swirl transitions revealing a corporate HVAC brand emblem.",
  },
  {
    id: "gotoken-app-logo",
    slug: "gotoken-app-logo",
    category: "logo-animation",
    title: "Go Token",
    description: "Expressive mascot face animation transitioning smoothly into a modern app icon and brand lockup.",
    thumbnail: "/images/prewiew/logo/token.webp",
    video: "/videos/animation/logo/token.webm",
    poster: "/images/projects/token.webp",
    showInMarquee: true,
    published: true,
    order: 10,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Character", "Crypto", "UI"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:04",
    seoTitle: "Go Token Character Motion | VL Motion",
    seoDescription: "Expressive mascot face animation transitioning smoothly into a modern app icon and brand lockup.",
  },
  {
    id: "palm-logo-reveal",
    slug: "palm-logo-reveal",
    category: "logo-animation",
    title: "Palm",
    description: "Minimalist glowing strokes constructing a typographic wordmark that blooms into a palm icon.",
    thumbnail: "/images/prewiew/logo/palm.webp",
    video: "/videos/animation/logo/palm.webm",
    poster: "/images/projects/palm.webp",
    showInMarquee: false,
    published: true,
    order: 11,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Minimal", "Nature", "Typography"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    seoTitle: "Palm Tree Wordmark | VL Motion",
    seoDescription: "Minimalist glowing strokes constructing a typographic wordmark that blooms into a palm icon.",
  },
  {
    id: "nexara-agency-logo",
    slug: "nexara-agency-logo",
    category: "logo-animation",
    title: "Nexara Agency",
    description: "Dynamic particle burst converging into a precise geometric grid and digital agency brand mark.",
    thumbnail: "/images/prewiew/logo/nexara.webp",
    video: "/videos/animation/logo/nexara.webm",
    poster: "/images/projects/nexara.webp",
    showInMarquee: false,
    published: true,
    order: 12,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects, Illustrator, Photoshop"],
    tags: ["Geometric", "Agency", "Particles"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Nexara Agency Motion | VL Motion",
    seoDescription: "Dynamic particle burst converging into a precise geometric grid and digital agency brand mark.",
  },
  {
  id: "paradise-found-logo",
  slug: "paradise-found",
  category: "logo-animation",
  title: "Paradise Found",
  description: "Smooth 2D vector logo animation featuring stroke reveals and retro typography.",
  thumbnail: "/images/prewiew/logo/paradise_found.webp",
  video: "/videos/animation/logo/paradise_found.webm",
  poster: "/images/projects/paradise_found.webp",
  showInMarquee: false,
  published: true,
  order: 6,
  client: "Personal project",
  year: "2026",
  tools: ["After Effects, Illustrator"],
  tags: ["Logo Animation", "Vector Graphics"],
  format: "1920x1080 / MP4",
  delivery: "Social Media / Web",
  duration: "9 sec",
  seoTitle: "Paradise Found Logo Animation | VL Motion",
  seoDescription: "A clean 2D vector logo animation featuring smooth stroke reveals and a retro aesthetic."
}
];

/*
 * ШАБЛОН ДЛЯ НОВОЇ РОБОТИ - скопіюй це в кінець масиву:
 * 
 * {
 *   id: "my-new-logo", // Унікальний ID
 *   slug: "my-new-logo", // Слаг URL
 *   category: "logo-animation",
 *   title: "My New Logo",
 *   description: "Опис",
 *   thumbnail: "/images/prewiew/logo/my-new-logo.webp",
 *   video: "/videos/animation/logo/my-new-logo.webm",
 *   poster: "/images/prewiew/logo/my-new-logo.webp",
 *   showInMarquee: true,
 *   published: true,
 *   order: 13,
 *   client: "Personal project",
 *   year: "2026",
 *   tools: ["After Effects"],
 *   tags: ["Logo"],
 *   format: "WEBM / MP4",
 *   delivery: "Logo package",
 *   duration: "0:05",
 *   seoTitle: "My New Logo | VL Motion",
 *   seoDescription: "Опис для Google",
 * },
 */
