/*
 * LOGO ANIMATION
 *
 * Тут тільки роботи цієї категорії.
 *
 * Для додавання відео зазвичай змінюєш:
 * - thumbnail — картинка картки;
 * - video — шлях до відео;
 * - poster — заставка відео;
 * - showInMarquee — показ у рухомій стрічці;
 * - published — показ роботи на сайті;
 * - order — порядок у цій категорії: 1, 2, 3...
 *
 * Картинка великої секції PROJECT задається окремо
 * у portfolioContent.ts в налаштуваннях категорій.
 * 
 * {
      id: "placeholder-orbit-logo",
      slug: "orbit-logo",
      title: "Orbit Logo Motion",
      category: "logo-animation",
      description: "A compact logo animation concept built around orbital movement and a precise final lockup.",
  
       Картинка картки. 
      thumbnail: "/images/projects/3.webp",
  
      Встав сюди шлях, коли відео буде готове. 
      video: "",
  
       Заставка відео. 
      poster: "/images/projects/4.webp",
  
       true = показувати у рухомій стрічці. 
      showInMarquee: false,
  
      true = показувати картку на сайті. 
      published: true,
  
       Порядок усередині цієї категорії. 
      order: 2,
  
      client: "Personal project",
      year: "2026",
      tools: ["After Effects"],
      tags: ["Future project"],
      format: "MP4 / WEBM",
      delivery: "Logo package",
      duration: "TBD",
  
      seoTitle: "Orbit Logo Motion | VL Motion",
      seoDescription: "A compact logo animation concept built around orbital movement and a precise final lockup.",
    }

*/
import type { PortfolioProject } from "../portfolioContent";

export const logoAnimationProjects: PortfolioProject[] = [

  
  {
    id: "techlogo-motion",
    slug: "techlogo-motion",
    title: "Techlogo Motion Reveal",
    category: "logo-animation",
    description: "Dynamic particle transformation into an interconnected tech symbol, completing with a sleek typographic reveal.",
    
    thumbnail: "/images/prewiew/logo/techlogo.webp",
    video: "/videos/animation/logo/techlogo.webm",
    poster: "/images/projects/techlogo.webp",
    
    showInMarquee: true,
    published: true,
    order: 1,
    
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Tech", "Abstract"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    
    seoTitle: "Techlogo Motion Reveal | VL Motion",
    seoDescription: "Dynamic particle transformation into an interconnected tech symbol, completing with a sleek typographic reveal.",
  },
  {
    id: "animation-designs-logo",
    slug: "animation-designs-logo",
    title: "Animation Designs Logo",
    category: "logo-animation",
    description: "Minimalist line dynamics leading into an infinity loop symbol with clean typography reveal.",
    
    thumbnail: "/images/prewiew/logo/animation-designs.webp",
    video: "/videos/animation/logo/animation-designs.webm",
    poster: "/images/prewiew/projects/3.webp",
    
    showInMarquee: true,
    published: true,
    order: 2,
    
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Minimal", "Infinity"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    
    seoTitle: "Animation Designs Logo | VL Motion",
    seoDescription: "Minimalist line dynamics leading into an infinity loop symbol with clean typography reveal.",
  },
  {
    id: "pycha-kebs-logo",
    slug: "pycha-kebs-logo",
    title: "Pycha Kebs Emblem",
    category: "logo-animation",
    description: "Dynamic animation of a vertical spit and chef's knife forming a classic street food emblem with bold typography.",
    thumbnail: "/images/prewiew/logo/pycha.webp",
    video: "/videos/animation/logo/pycha.webm",
    poster: "/videos/animation/logo/pycha.webp",
    showInMarquee: true,
    published: true,
    order: 1,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Food", "Emblem", "Dynamic"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    seoTitle: "Pycha Kebs Emblem | VL Motion",
    seoDescription: "Dynamic animation of a vertical spit and chef's knife forming a classic street food emblem with bold typography.",
  },
  {
    id: "coolinart-logo",
    slug: "coolinart-logo",
    title: "Coolinart Identity",
    category: "logo-animation",
    description: "Playful character-driven animation featuring a chef's hat and eyes that seamlessly transition into custom typography.",
    thumbnail: "/images/prewiew/logo/coolinart.webp",
    video: "/videos/animation/logo/coolinart.webm",
    poster: "/images/projects/coolinart.webp",
    showInMarquee: true,
    published: true,
    order: 2,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Character", "Playful", "Food"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:07",
    seoTitle: "Coolinart Identity Reveal | VL Motion",
    seoDescription: "Playful character-driven animation featuring a chef's hat and eyes that seamlessly transition into custom typography.",
  },
  {
    id: "foodtalk-logo",
    slug: "foodtalk-logo",
    title: "Food Talk Concept",
    category: "logo-animation",
    description: "Minimalist animation starting with messaging indicators that morph into a speech bubble with integrated cutlery icons.",
    thumbnail: "/images/prewiew/logo/foodtalk.webp",
    video: "/videos/animation/logo/foodtalk.webm",
    poster: "/images/projects/foodtalk.webp",
    showInMarquee: true,
    published: true,
    order: 3,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Minimal", "Morphing", "UI"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:07",
    seoTitle: "Food Talk Concept | VL Motion",
    seoDescription: "Minimalist animation starting with messaging indicators that morph into a speech bubble with integrated cutlery icons.",
  },
  {
    id: "enigma-logo",
    slug: "enigma-logo",
    title: "Enigma Pattern Motion",
    category: "logo-animation",
    description: "Geometric transformation of intersecting layers evolving into a complex, elegant pattern and luxury emblem.",
    thumbnail: "/images/prewiew/logo/enigma.webp",
    video: "/videos/animation/logo/enigma.webm",
    poster: "/images/projects/enigma.webp",
    showInMarquee: true,
    published: true,
    order: 4,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Geometric", "Luxury", "Pattern"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:10",
    seoTitle: "Enigma Logo Animation | VL Motion",
    seoDescription: "Geometric transformation of intersecting layers evolving into a complex, elegant pattern and luxury emblem.",
  },
  {
    id: "bbq-restaurant-logo",
    slug: "bbq-restaurant-logo",
    title: "Barbecue Restaurant Emblem",
    category: "logo-animation",
    description: "Constructivist geometric transitions resolving into a detailed vintage-style beef cattle logo badge.",
    thumbnail: "/images/prewiew/logo/bbq.webp",
    video: "/videos/animation/logo/bbq.webm",
    poster: "/images/projects/bbq.webp",
    showInMarquee: true,
    published: true,
    order: 5,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Vintage", "Badge", "Geometric"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Barbecue Restaurant Emblem | VL Motion",
    seoDescription: "Constructivist geometric transitions resolving into a detailed vintage-style beef cattle logo badge.",
  },
  {
    id: "frame-logo-motion",
    slug: "frame-logo-motion",
    title: "Frame Focus Reveal",
    category: "logo-animation",
    description: "Camera focusing animation with green viewfinder corners revealing dynamic modern typography.",
    thumbnail: "/images/prewiew/logo/frame.webp",
    video: "/videos/animation/logo/frame.webm",
    poster: "/images/projects/frame.webp",
    showInMarquee: true,
    published: true,
    order: 6,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Tech", "Focus", "Clean"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:04",
    seoTitle: "Frame Focus Reveal | VL Motion",
    seoDescription: "Camera focusing animation with green viewfinder corners revealing dynamic modern typography.",
  },
  {
    id: "grant-heating-cooling",
    slug: "grant-heating-cooling",
    title: "Grant Industrial Identity",
    category: "logo-animation",
    description: "Sleek fluid motion and dynamic swirl transitions revealing a corporate HVAC brand emblem.",
    thumbnail: "/images/prewiew/logo/grant.webp",
    video: "/videos/animation/logo/grant.webm",
    poster: "/images/projects/grant.webp",
    showInMarquee: false,
    published: true,
    order: 7,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Corporate", "Fluid", "HVAC"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Grant Industrial Identity | VL Motion",
    seoDescription: "Sleek fluid motion and dynamic swirl transitions revealing a corporate HVAC brand emblem.",
  },
  {
    id: "gotoken-app-logo",
    slug: "gotoken-app-logo",
    title: "Go Token Character Motion",
    category: "logo-animation",
    description: "Expressive mascot face animation transitioning smoothly into a modern app icon and brand lockup.",
    thumbnail: "/images/prewiew/logo/token.webp",
    video: "/videos/animation/logo/token.webm",
    poster: "/images/projects/token.webp",
    showInMarquee: true,
    published: true,
    order: 8,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Character", "Crypto", "UI"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:04",
    seoTitle: "Go Token Character Motion | VL Motion",
    seoDescription: "Expressive mascot face animation transitioning smoothly into a modern app icon and brand lockup.",
  },
  {
    id: "palm-logo-reveal",
    slug: "palm-logo-reveal",
    title: "Palm Tree Wordmark",
    category: "logo-animation",
    description: "Minimalist glowing strokes constructing a typographic wordmark that blooms into a palm icon.",
    thumbnail: "/images/prewiew/logo/palm.webp",
    video: "/videos/animation/logo/palm.webm",
    poster: "/images/projects/palm.webp",
    showInMarquee: false,
    published: true,
    order: 9,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Minimal", "Nature", "Typography"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:05",
    seoTitle: "Palm Tree Wordmark | VL Motion",
    seoDescription: "Minimalist glowing strokes constructing a typographic wordmark that blooms into a palm icon.",
  },
  {
    id: "nexara-agency-logo",
    slug: "nexara-agency-logo",
    title: "Nexara Agency Motion",
    category: "logo-animation",
    description: "Dynamic particle burst converging into a precise geometric grid and digital agency brand mark.",
    thumbnail: "/images/prewiew/logo/nexara.webp",
    video: "/videos/animation/logo/nexara.webm",
    poster: "/images/projects/nexara.webp",
    showInMarquee: false,
    published: true,
    order: 10,
    client: "Personal project",
    year: "2026",
    tools: ["After Effects"],
    tags: ["Geometric", "Agency", "Particles"],
    format: "WEBM / MP4",
    delivery: "Logo package",
    duration: "0:06",
    seoTitle: "Nexara Agency Motion | VL Motion",
    seoDescription: "Dynamic particle burst converging into a precise geometric grid and digital agency brand mark.",
  }

];
